-- ============================================================================
-- CLEAN SETUP SCRIPT - Removes old data and sets up Location + Status fresh
-- Run this to fix duplicates and set up everything cleanly
-- ============================================================================

-- ============================================================================
-- STEP 1: CLEAN UP EXISTING DATA
-- ============================================================================

-- Remove foreign key constraints from Booking first
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE Booking DROP CONSTRAINT fk_booking_pickup_loc';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE Booking DROP CONSTRAINT fk_booking_dropoff_loc';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Drop indexes
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_booking_pickup_loc'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_booking_dropoff_loc'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_location_city'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_location_state'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_location_active'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_car_status'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_booking_status'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP INDEX idx_booking_created_at'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Clear location IDs from Booking
UPDATE Booking SET pickup_location_id = NULL, dropoff_location_id = NULL;
COMMIT;

-- Drop Location table completely
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Location CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ============================================================================
-- STEP 2: CREATE FRESH LOCATION TABLE
-- ============================================================================
CREATE TABLE Location (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    state VARCHAR2(100) NOT NULL,
    postal_code VARCHAR2(20),
    country VARCHAR2(50) DEFAULT 'Malaysia',
    phone VARCHAR2(20),
    email VARCHAR2(100),
    opening_time VARCHAR2(10) DEFAULT '08:00',
    closing_time VARCHAR2(10) DEFAULT '22:00',
    is_airport NUMBER(1) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1,
    CONSTRAINT chk_location_airport CHECK (is_airport IN (0, 1)),
    CONSTRAINT chk_location_active CHECK (is_active IN (0, 1))
);

-- ============================================================================
-- STEP 3: INSERT 18 LOCATIONS (NO DUPLICATES)
-- ============================================================================

-- Airports (5)
INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('KLIA', 'KL International Airport, Level 3', 'Sepang', 'Selangor', '64000', '+60-3-8787-3000', 'klia@carola.my', '00:00', '23:59', 1);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('KLIA2', 'KL International Airport 2', 'Sepang', 'Selangor', '64000', '+60-3-8787-4000', 'klia2@carola.my', '00:00', '23:59', 1);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Subang Airport', 'Sultan Abdul Aziz Shah Airport', 'Subang', 'Selangor', '47200', '+60-3-7846-7890', 'subang@carola.my', '06:00', '23:00', 1);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Penang Airport', 'Penang International Airport', 'Bayan Lepas', 'Penang', '11900', '+60-4-643-4411', 'penang@carola.my', '00:00', '23:59', 1);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Senai Airport', 'Senai International Airport', 'Senai', 'Johor', '81250', '+60-7-599-4500', 'senai@carola.my', '00:00', '23:59', 1);

-- Kuala Lumpur (4)
INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('KL Sentral', 'Stesen Sentral Kuala Lumpur', 'Kuala Lumpur', 'Wilayah Persekutuan', '50470', '+60-3-2260-1000', 'klsentral@carola.my', '07:00', '23:00', 0);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Mid Valley', 'Mid Valley Megamall', 'Kuala Lumpur', 'Wilayah Persekutuan', '59200', '+60-3-2938-3333', 'midvalley@carola.my', '10:00', '22:00', 0);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Pavilion KL', 'Pavilion Kuala Lumpur', 'Kuala Lumpur', 'Wilayah Persekutuan', '55100', '+60-3-2118-8833', 'pavilion@carola.my', '10:00', '22:00', 0);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Bangsar', 'Bangsar Village II', 'Kuala Lumpur', 'Wilayah Persekutuan', '59100', '+60-3-2282-1808', 'bangsar@carola.my', '10:00', '22:00', 0);

-- Selangor (4)
INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Cyberjaya', 'D''Pulze Shopping Centre', 'Cyberjaya', 'Selangor', '63000', '+60-3-8320-8888', 'cyberjaya@carola.my', '10:00', '22:00', 0);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Putrajaya', 'IOI City Mall', 'Putrajaya', 'Wilayah Persekutuan', '62502', '+60-3-8328-8888', 'putrajaya@carola.my', '10:00', '22:00', 0);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Petaling Jaya', 'Jaya One', 'Petaling Jaya', 'Selangor', '46200', '+60-3-7960-0288', 'pj@carola.my', '09:00', '21:00', 0);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Shah Alam', 'SACC Mall', 'Shah Alam', 'Selangor', '40000', '+60-3-5510-6868', 'shahalam@carola.my', '10:00', '22:00', 0);

-- Penang (1)
INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Georgetown', 'Komtar', 'Georgetown', 'Penang', '10000', '+60-4-262-6262', 'georgetown@carola.my', '10:00', '22:00', 0);

-- Johor (1)
INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('JB Sentral', 'JB Sentral Station', 'Johor Bahru', 'Johor', '80000', '+60-7-226-6666', 'jbsentral@carola.my', '06:00', '23:00', 0);

-- Other States (2)
INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Ipoh', 'Ipoh Parade', 'Ipoh', 'Perak', '30000', '+60-5-255-8888', 'ipoh@carola.my', '10:00', '22:00', 0);

INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
VALUES ('Melaka', 'Dataran Pahlawan', 'Melaka', 'Melaka', '75000', '+60-6-282-8888', 'melaka@carola.my', '10:00', '22:00', 0);

COMMIT;

-- ============================================================================
-- STEP 4: ADD BOOKING LOCATION COLUMNS (if not exist)
-- ============================================================================
DECLARE
    col_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM user_tab_columns 
    WHERE table_name = 'BOOKING' AND column_name = 'PICKUP_LOCATION_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD pickup_location_id NUMBER';
    END IF;
    
    SELECT COUNT(*) INTO col_exists FROM user_tab_columns 
    WHERE table_name = 'BOOKING' AND column_name = 'DROPOFF_LOCATION_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD dropoff_location_id NUMBER';
    END IF;
END;
/

-- Add foreign key constraints
ALTER TABLE Booking ADD CONSTRAINT fk_booking_pickup_loc 
    FOREIGN KEY (pickup_location_id) REFERENCES Location(location_id);
    
ALTER TABLE Booking ADD CONSTRAINT fk_booking_dropoff_loc 
    FOREIGN KEY (dropoff_location_id) REFERENCES Location(location_id);

-- ============================================================================
-- STEP 5: ADD CAR STATUS (if not exist)
-- ============================================================================
DECLARE
    col_exists NUMBER;
    constraint_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM user_tab_columns 
    WHERE table_name = 'CAR' AND column_name = 'CAR_STATUS';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Car ADD car_status VARCHAR2(20) DEFAULT ''Available''';
    END IF;
    
    SELECT COUNT(*) INTO constraint_exists FROM user_constraints 
    WHERE constraint_name = 'CHK_CAR_STATUS';
    IF constraint_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Car ADD CONSTRAINT chk_car_status CHECK (car_status IN (''Available'', ''Rented'', ''Maintenance'', ''Dirty''))';
    END IF;
END;
/

-- ============================================================================
-- STEP 6: ADD BOOKING STATUS (if not exist)
-- ============================================================================
DECLARE
    col_exists NUMBER;
    constraint_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO col_exists FROM user_tab_columns 
    WHERE table_name = 'BOOKING' AND column_name = 'BOOKING_STATUS';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD booking_status VARCHAR2(20) DEFAULT ''Confirmed''';
    END IF;
    
    SELECT COUNT(*) INTO col_exists FROM user_tab_columns 
    WHERE table_name = 'BOOKING' AND column_name = 'CREATED_AT';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD created_at DATE DEFAULT SYSDATE';
    END IF;
    
    SELECT COUNT(*) INTO constraint_exists FROM user_constraints 
    WHERE constraint_name = 'CHK_BOOKING_STATUS';
    IF constraint_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD CONSTRAINT chk_booking_status CHECK (booking_status IN (''Confirmed'', ''In Progress'', ''Completed'', ''Cancelled''))';
    END IF;
END;
/

COMMIT;

-- ============================================================================
-- STEP 7: CREATE INDEXES
-- ============================================================================
CREATE INDEX idx_booking_pickup_loc ON Booking(pickup_location_id);
CREATE INDEX idx_booking_dropoff_loc ON Booking(dropoff_location_id);
CREATE INDEX idx_location_city ON Location(city);
CREATE INDEX idx_car_status ON Car(car_status);
CREATE INDEX idx_booking_status ON Booking(booking_status);

COMMIT;

-- ============================================================================
-- VERIFICATION - Should show exactly 18 locations
-- ============================================================================
SELECT 'Total Locations: ' || COUNT(*) as result FROM Location;
SELECT location_id, location_name, city, is_airport FROM Location ORDER BY location_id;



