-- ============================================================================
-- LOCATION TABLE MIGRATION SCRIPT (IDEMPOTENT - Safe to run multiple times)
-- Creates a Location table for managing branch addresses, hours, and contact info
-- Updates Booking table to use foreign keys for pickup/dropoff locations
-- ============================================================================

-- ============================================================================
-- STEP 1: CREATE LOCATION TABLE (if not exists)
-- ============================================================================
DECLARE
    table_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO table_exists FROM user_tables WHERE table_name = 'LOCATION';
    IF table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE Location (
                location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                location_name VARCHAR2(100) NOT NULL,
                address VARCHAR2(255) NOT NULL,
                city VARCHAR2(100) NOT NULL,
                state VARCHAR2(100) NOT NULL,
                postal_code VARCHAR2(20),
                country VARCHAR2(50) DEFAULT ''Malaysia'',
                phone VARCHAR2(20),
                email VARCHAR2(100),
                opening_time VARCHAR2(10) DEFAULT ''08:00'',
                closing_time VARCHAR2(10) DEFAULT ''22:00'',
                is_airport NUMBER(1) DEFAULT 0,
                is_active NUMBER(1) DEFAULT 1,
                CONSTRAINT chk_location_airport CHECK (is_airport IN (0, 1)),
                CONSTRAINT chk_location_active CHECK (is_active IN (0, 1))
            )';
        DBMS_OUTPUT.PUT_LINE('Location table created.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Location table already exists.');
    END IF;
END;
/

-- ============================================================================
-- STEP 2: INSERT LOCATIONS (only if table is empty)
-- ============================================================================
DECLARE
    loc_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO loc_count FROM Location;
    IF loc_count = 0 THEN
        -- Airports
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('KLIA', 'KL International Airport, Departure Hall Level 3', 'Sepang', 'Selangor', '64000', '+60-3-8787-3000', 'klia@carola.my', '00:00', '23:59', 1);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('KLIA2', 'KL International Airport 2, Arrival Hall', 'Sepang', 'Selangor', '64000', '+60-3-8787-4000', 'klia2@carola.my', '00:00', '23:59', 1);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Subang Airport', 'Sultan Abdul Aziz Shah Airport', 'Subang', 'Selangor', '47200', '+60-3-7846-7890', 'subang@carola.my', '06:00', '23:00', 1);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Penang Airport', 'Penang International Airport, Arrival Hall', 'Bayan Lepas', 'Penang', '11900', '+60-4-643-4411', 'penang@carola.my', '00:00', '23:59', 1);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Senai Airport', 'Senai International Airport, Arrival Hall', 'Senai', 'Johor', '81250', '+60-7-599-4500', 'senai@carola.my', '00:00', '23:59', 1);
        
        -- Kuala Lumpur & Selangor
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('KL Sentral', 'Stesen Sentral Kuala Lumpur, Level G', 'Kuala Lumpur', 'Wilayah Persekutuan', '50470', '+60-3-2260-1000', 'klsentral@carola.my', '07:00', '23:00', 0);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Mid Valley', 'Mid Valley Megamall, Basement 2', 'Kuala Lumpur', 'Wilayah Persekutuan', '59200', '+60-3-2938-3333', 'midvalley@carola.my', '10:00', '22:00', 0);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Pavilion KL', 'Pavilion Kuala Lumpur, Level B2', 'Kuala Lumpur', 'Wilayah Persekutuan', '55100', '+60-3-2118-8833', 'pavilion@carola.my', '10:00', '22:00', 0);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Bangsar', 'Bangsar Village II, Ground Floor', 'Kuala Lumpur', 'Wilayah Persekutuan', '59100', '+60-3-2282-1808', 'bangsar@carola.my', '10:00', '22:00', 0);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Cyberjaya', 'D''Pulze Shopping Centre', 'Cyberjaya', 'Selangor', '63000', '+60-3-8320-8888', 'cyberjaya@carola.my', '10:00', '22:00', 0);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Putrajaya', 'IOI City Mall, Level LG', 'Putrajaya', 'Wilayah Persekutuan', '62502', '+60-3-8328-8888', 'putrajaya@carola.my', '10:00', '22:00', 0);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Petaling Jaya', 'Jaya One, Jalan Universiti', 'Petaling Jaya', 'Selangor', '46200', '+60-3-7960-0288', 'pj@carola.my', '09:00', '21:00', 0);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Shah Alam', 'SACC Mall, Seksyen 7', 'Shah Alam', 'Selangor', '40000', '+60-3-5510-6868', 'shahalam@carola.my', '10:00', '22:00', 0);
        
        -- Penang
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Georgetown', 'Komtar, Level 3', 'Georgetown', 'Penang', '10000', '+60-4-262-6262', 'georgetown@carola.my', '10:00', '22:00', 0);
        
        -- Johor
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('JB Sentral', 'JB Sentral, Ground Floor', 'Johor Bahru', 'Johor', '80000', '+60-7-226-6666', 'jbsentral@carola.my', '06:00', '23:00', 0);
        
        -- Other States
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Ipoh', 'Ipoh Parade, Ground Floor', 'Ipoh', 'Perak', '30000', '+60-5-255-8888', 'ipoh@carola.my', '10:00', '22:00', 0);
        
        INSERT INTO Location (location_name, address, city, state, postal_code, phone, email, opening_time, closing_time, is_airport)
        VALUES ('Melaka', 'Dataran Pahlawan, Level G', 'Melaka', 'Melaka', '75000', '+60-6-282-8888', 'melaka@carola.my', '10:00', '22:00', 0);
        
        DBMS_OUTPUT.PUT_LINE('Inserted 18 locations.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('Locations already exist (' || loc_count || ' found). Skipping inserts.');
    END IF;
END;
/

COMMIT;

-- ============================================================================
-- STEP 3: ADD COLUMNS TO BOOKING TABLE (if not exist)
-- ============================================================================
DECLARE
    col_exists NUMBER;
BEGIN
    -- Check pickup_location_id
    SELECT COUNT(*) INTO col_exists FROM user_tab_columns 
    WHERE table_name = 'BOOKING' AND column_name = 'PICKUP_LOCATION_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD pickup_location_id NUMBER';
        DBMS_OUTPUT.PUT_LINE('Added pickup_location_id column.');
    END IF;
    
    -- Check dropoff_location_id
    SELECT COUNT(*) INTO col_exists FROM user_tab_columns 
    WHERE table_name = 'BOOKING' AND column_name = 'DROPOFF_LOCATION_ID';
    IF col_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD dropoff_location_id NUMBER';
        DBMS_OUTPUT.PUT_LINE('Added dropoff_location_id column.');
    END IF;
END;
/

-- ============================================================================
-- STEP 4: ADD CONSTRAINTS (if not exist)
-- ============================================================================
DECLARE
    constraint_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO constraint_exists FROM user_constraints 
    WHERE constraint_name = 'FK_BOOKING_PICKUP_LOC';
    IF constraint_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD CONSTRAINT fk_booking_pickup_loc FOREIGN KEY (pickup_location_id) REFERENCES Location(location_id)';
        DBMS_OUTPUT.PUT_LINE('Added FK constraint for pickup_location_id.');
    END IF;
    
    SELECT COUNT(*) INTO constraint_exists FROM user_constraints 
    WHERE constraint_name = 'FK_BOOKING_DROPOFF_LOC';
    IF constraint_exists = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE Booking ADD CONSTRAINT fk_booking_dropoff_loc FOREIGN KEY (dropoff_location_id) REFERENCES Location(location_id)';
        DBMS_OUTPUT.PUT_LINE('Added FK constraint for dropoff_location_id.');
    END IF;
END;
/

-- ============================================================================
-- STEP 5: MIGRATE EXISTING BOOKING DATA
-- ============================================================================
UPDATE Booking b
SET pickup_location_id = (
    SELECT l.location_id 
    FROM Location l 
    WHERE UPPER(b.pickup_location) LIKE '%' || UPPER(l.location_name) || '%'
    AND ROWNUM = 1
)
WHERE pickup_location IS NOT NULL AND pickup_location_id IS NULL;

UPDATE Booking b
SET dropoff_location_id = (
    SELECT l.location_id 
    FROM Location l 
    WHERE UPPER(b.dropoff_location) LIKE '%' || UPPER(l.location_name) || '%'
    AND ROWNUM = 1
)
WHERE dropoff_location IS NOT NULL AND dropoff_location_id IS NULL;

COMMIT;

-- ============================================================================
-- STEP 6: CREATE INDEXES (if not exist)
-- ============================================================================
DECLARE
    idx_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO idx_exists FROM user_indexes WHERE index_name = 'IDX_BOOKING_PICKUP_LOC';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_booking_pickup_loc ON Booking(pickup_location_id)';
    END IF;
    
    SELECT COUNT(*) INTO idx_exists FROM user_indexes WHERE index_name = 'IDX_BOOKING_DROPOFF_LOC';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_booking_dropoff_loc ON Booking(dropoff_location_id)';
    END IF;
    
    SELECT COUNT(*) INTO idx_exists FROM user_indexes WHERE index_name = 'IDX_LOCATION_CITY';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_location_city ON Location(city)';
    END IF;
    
    SELECT COUNT(*) INTO idx_exists FROM user_indexes WHERE index_name = 'IDX_LOCATION_STATE';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_location_state ON Location(state)';
    END IF;
    
    SELECT COUNT(*) INTO idx_exists FROM user_indexes WHERE index_name = 'IDX_LOCATION_ACTIVE';
    IF idx_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_location_active ON Location(is_active)';
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('Indexes checked/created.');
END;
/

COMMIT;

-- ============================================================================
-- VERIFICATION
-- ============================================================================
SELECT 'Locations: ' || COUNT(*) as result FROM Location;
SELECT 'Bookings with pickup_location_id: ' || COUNT(*) as result FROM Booking WHERE pickup_location_id IS NOT NULL;
