-- Create Brand Table
CREATE TABLE Brand (
    brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(100) NOT NULL
);

-- Create Customer Table
CREATE TABLE Customer (
    cust_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_fname VARCHAR2(50) NOT NULL,
    cust_lname VARCHAR2(50) NOT NULL,
    cust_age NUMBER,
    cust_email VARCHAR2(100) UNIQUE NOT NULL,
    cust_phone VARCHAR2(20),
    cust_username VARCHAR2(50) UNIQUE NOT NULL,
    cust_password VARCHAR2(100) NOT NULL
);

-- Create Staff Table (Self-Referencing)
CREATE TABLE Staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_fname VARCHAR2(50) NOT NULL,
    staff_lname VARCHAR2(50) NOT NULL,
    staff_email VARCHAR2(100) UNIQUE NOT NULL,
    staff_phone VARCHAR2(20),
    staff_dept VARCHAR2(50),
    staff_username VARCHAR2(50) UNIQUE NOT NULL,
    staff_password VARCHAR2(100) NOT NULL,
    manager_id NUMBER
);

-- Add Self-Referencing Foreign Key for Manager
ALTER TABLE Staff
ADD CONSTRAINT fk_staff_manager
FOREIGN KEY (manager_id) REFERENCES Staff(staff_id);

-- 3. CREATE LOOKUP AND INTERMEDIATE TABLES

-- Create Model Table
CREATE TABLE Model (
    model_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR2(100) NOT NULL,
    brand_id NUMBER NOT NULL,
    CONSTRAINT fk_model_brand FOREIGN KEY (brand_id) REFERENCES Brand(brand_id)
);

-- Create CarType Table
CREATE TABLE CarType (
    carType_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carType_name VARCHAR2(50) NOT NULL,
    carType_description VARCHAR2(255)
);

-- 4. CREATE MAIN ENTITY (CAR) - WITH LOCATION FIELDS

CREATE TABLE Car (
    car_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id NUMBER NOT NULL,
    carType_id NUMBER NOT NULL,
    rate NUMBER(10, 2) NOT NULL,
    description VARCHAR2(255),
    door NUMBER,
    suitcase NUMBER,
    seat NUMBER,
    attachments VARCHAR2(255),
    colour VARCHAR2(50),
    -- ✅ NEW LOCATION FIELDS
    pickup_location VARCHAR2(255),
    dropoff_location VARCHAR2(255),
    available_locations VARCHAR2(500),
    allows_different_dropoff NUMBER(1) DEFAULT 1,
    -- Constraints
    CONSTRAINT fk_car_model FOREIGN KEY (model_id) REFERENCES Model(model_id),
    CONSTRAINT fk_car_type FOREIGN KEY (carType_id) REFERENCES CarType(carType_id),
    CONSTRAINT chk_allows_different_dropoff CHECK (allows_different_dropoff IN (0, 1))
);

-- Note: Removed unnecessary circular FK from CarType to Car
-- CarType → Car is the correct one-to-many relationship

-- 5. CREATE SUBTYPE TABLES (Inheritance)

-- Petrol Car
CREATE TABLE Petrol (
    car_id NUMBER PRIMARY KEY,
    octane_rating NUMBER,
    fuel_tank_capacity NUMBER,
    CONSTRAINT fk_petrol_car FOREIGN KEY (car_id) REFERENCES Car(car_id)
);

-- Diesel Car
CREATE TABLE Diesel (
    car_id NUMBER PRIMARY KEY,
    diesel_emission VARCHAR2(50),
    fuel_tank_capacity NUMBER,
    CONSTRAINT fk_diesel_car FOREIGN KEY (car_id) REFERENCES Car(car_id)
);

-- Electric Car
CREATE TABLE Electric (
    car_id NUMBER PRIMARY KEY,
    battery_range NUMBER,
    charging_rate_kw NUMBER,
    last_charging_date DATE,
    CONSTRAINT fk_electric_car FOREIGN KEY (car_id) REFERENCES Car(car_id)
);

-- 6. CREATE TRANSACTIONAL TABLES

-- Create Booking Table
CREATE TABLE Booking (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_id NUMBER NOT NULL,
    staff_id NUMBER NOT NULL,
    car_id NUMBER NOT NULL,
    pickup_date DATE NOT NULL,
    dropoff_date DATE NOT NULL,
    pickup_location VARCHAR2(100),
    dropoff_location VARCHAR2(100),
    price NUMBER(10, 2),
    CONSTRAINT fk_booking_cust FOREIGN KEY (cust_id) REFERENCES Customer(cust_id),
    CONSTRAINT fk_booking_staff FOREIGN KEY (staff_id) REFERENCES Staff(staff_id),
    CONSTRAINT fk_booking_car FOREIGN KEY (car_id) REFERENCES Car(car_id)
);

-- Create Payment Table (1:1 with Booking)
CREATE TABLE Payment (
    booking_id NUMBER PRIMARY KEY,
    amount NUMBER(10, 2) NOT NULL,
    payment_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES Booking(booking_id)
);

-- 7. CREATE INDEXES FOR PERFORMANCE
CREATE INDEX idx_car_pickup_location ON Car(pickup_location);
CREATE INDEX idx_car_allows_dropoff ON Car(allows_different_dropoff);
CREATE INDEX idx_booking_pickup_date ON Booking(pickup_date);
CREATE INDEX idx_booking_dropoff_date ON Booking(dropoff_date);

COMMIT;