-- ============================================================================
-- CAROLA CAR RENTAL - DATABASE SCHEMA
-- Supports Fleet Inventory: Multiple cars per model at different locations
-- ============================================================================

-- 1. CREATE CORE LOOKUP TABLES
-- ============================================================================

-- Create Brand Table
CREATE TABLE Brand (
    brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR2(100) NOT NULL
);

-- Create CarType Table
CREATE TABLE CarType (
    carType_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carType_name VARCHAR2(50) NOT NULL,
    carType_description VARCHAR2(255)
);

-- 2. CREATE USER TABLES
-- ============================================================================

-- Create Customer Table
CREATE TABLE Customer (
    cust_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_fname VARCHAR2(50) NOT NULL,
    cust_lname VARCHAR2(50) NOT NULL,
    cust_age NUMBER,
    cust_email VARCHAR2(100) UNIQUE NOT NULL,
    cust_phone VARCHAR2(20),
    cust_username VARCHAR2(50) UNIQUE NOT NULL,
    cust_password VARCHAR2(100) NOT NULL
);

-- Create Staff Table (Self-Referencing)
CREATE TABLE Staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_fname VARCHAR2(50) NOT NULL,
    staff_lname VARCHAR2(50) NOT NULL,
    staff_email VARCHAR2(100) UNIQUE NOT NULL,
    staff_phone VARCHAR2(20),
    staff_dept VARCHAR2(50),
    staff_username VARCHAR2(50) UNIQUE NOT NULL,
    staff_password VARCHAR2(100) NOT NULL,
    manager_id NUMBER
);

-- Add Self-Referencing Foreign Key for Manager
ALTER TABLE Staff
ADD CONSTRAINT fk_staff_manager
FOREIGN KEY (manager_id) REFERENCES Staff(staff_id);

-- 3. CREATE MODEL TABLE (depends on Brand)
-- ============================================================================

CREATE TABLE Model (
    model_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR2(100) NOT NULL,
    brand_id NUMBER NOT NULL,
    attachments VARCHAR2(255),  -- Model image (shared by all cars of this model)
    CONSTRAINT fk_model_brand FOREIGN KEY (brand_id) REFERENCES Brand(brand_id)
);

-- 4. CREATE LOCATION TABLE (for branch management)
-- ============================================================================
-- MUST be created before Car table (Car references Location)

CREATE TABLE Location (
    location_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(255) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    state VARCHAR2(100) NOT NULL,
    postal_code VARCHAR2(20),
    country VARCHAR2(50) DEFAULT 'Malaysia',
    phone VARCHAR2(20),
    email VARCHAR2(100),
    opening_time VARCHAR2(10) DEFAULT '08:00',
    closing_time VARCHAR2(10) DEFAULT '22:00',
    is_airport NUMBER(1) DEFAULT 0,
    is_active NUMBER(1) DEFAULT 1,
    CONSTRAINT chk_location_airport CHECK (is_airport IN (0, 1)),
    CONSTRAINT chk_location_active CHECK (is_active IN (0, 1))
);

-- 5. CREATE CAR TABLE (FLEET INVENTORY)
-- ============================================================================
-- Each row = one physical car unit at a specific location
-- Same model can have multiple cars at different locations

CREATE TABLE Car (
    car_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id NUMBER NOT NULL,
    carType_id NUMBER NOT NULL,
    rate NUMBER(10, 2) NOT NULL,
    description VARCHAR2(255),
    door NUMBER,
    suitcase NUMBER,
    seat NUMBER,
    colour VARCHAR2(50),
    -- ✅ CAR STATUS: Available, Rented, Maintenance, Dirty
    car_status VARCHAR2(20) DEFAULT 'Available',
    -- ✅ FLEET INVENTORY: Each physical car has a home location
    location_id NUMBER NOT NULL,           -- FK to Location (car's home base)
    allows_different_dropoff NUMBER(1) DEFAULT 1,
    -- Constraints
    CONSTRAINT fk_car_model FOREIGN KEY (model_id) REFERENCES Model(model_id),
    CONSTRAINT fk_car_type FOREIGN KEY (carType_id) REFERENCES CarType(carType_id),
    CONSTRAINT fk_car_location FOREIGN KEY (location_id) REFERENCES Location(location_id),
    CONSTRAINT chk_allows_different_dropoff CHECK (allows_different_dropoff IN (0, 1)),
    CONSTRAINT chk_car_status CHECK (car_status IN ('Available', 'Rented', 'Maintenance', 'Dirty'))
);

-- 6. CREATE FUEL SUBTYPE TABLES (Inheritance)
-- ============================================================================

-- Petrol Car
CREATE TABLE Petrol (
    car_id NUMBER PRIMARY KEY,
    octane_rating NUMBER,
    fuel_tank_capacity NUMBER,
    CONSTRAINT fk_petrol_car FOREIGN KEY (car_id) REFERENCES Car(car_id)
);

-- Diesel Car
CREATE TABLE Diesel (
    car_id NUMBER PRIMARY KEY,
    diesel_emission VARCHAR2(50),
    fuel_tank_capacity NUMBER,
    CONSTRAINT fk_diesel_car FOREIGN KEY (car_id) REFERENCES Car(car_id)
);

-- Electric Car
CREATE TABLE Electric (
    car_id NUMBER PRIMARY KEY,
    battery_range NUMBER,
    charging_rate_kw NUMBER,
    last_charging_date DATE,
    CONSTRAINT fk_electric_car FOREIGN KEY (car_id) REFERENCES Car(car_id)
);

-- 7. CREATE TRANSACTIONAL TABLES
-- ============================================================================

-- Create Booking Table
CREATE TABLE Booking (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_id NUMBER NOT NULL,
    staff_id NUMBER NOT NULL,
    car_id NUMBER NOT NULL,
    pickup_date DATE NOT NULL,
    dropoff_date DATE NOT NULL,
    pickup_location_id NUMBER,
    dropoff_location_id NUMBER,
    price NUMBER(10, 2),
    -- ✅ BOOKING STATUS: Confirmed, In Progress, Completed, Cancelled
    booking_status VARCHAR2(20) DEFAULT 'Confirmed',
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_booking_cust FOREIGN KEY (cust_id) REFERENCES Customer(cust_id),
    CONSTRAINT fk_booking_staff FOREIGN KEY (staff_id) REFERENCES Staff(staff_id),
    CONSTRAINT fk_booking_car FOREIGN KEY (car_id) REFERENCES Car(car_id),
    CONSTRAINT fk_booking_pickup_loc FOREIGN KEY (pickup_location_id) REFERENCES Location(location_id),
    CONSTRAINT fk_booking_dropoff_loc FOREIGN KEY (dropoff_location_id) REFERENCES Location(location_id),
    CONSTRAINT chk_booking_status CHECK (booking_status IN ('Confirmed', 'In Progress', 'Completed', 'Cancelled'))
);

-- Create Payment Table (1:1 with Booking)
CREATE TABLE Payment (
    booking_id NUMBER PRIMARY KEY,
    amount NUMBER(10, 2) NOT NULL,
    payment_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id) REFERENCES Booking(booking_id)
);

-- 8. CREATE INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX idx_car_location ON Car(location_id);
CREATE INDEX idx_car_status ON Car(car_status);
CREATE INDEX idx_car_allows_dropoff ON Car(allows_different_dropoff);
CREATE INDEX idx_booking_pickup_date ON Booking(pickup_date);
CREATE INDEX idx_booking_dropoff_date ON Booking(dropoff_date);
CREATE INDEX idx_booking_pickup_loc ON Booking(pickup_location_id);
CREATE INDEX idx_booking_dropoff_loc ON Booking(dropoff_location_id);
CREATE INDEX idx_booking_status ON Booking(booking_status);
CREATE INDEX idx_location_city ON Location(city);
CREATE INDEX idx_location_state ON Location(state);
CREATE INDEX idx_location_active ON Location(is_active);

COMMIT;
